### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by ananosleep**
platform: windows 10 and python 3.10.14
gradio 4.22.0 launch with error:
`UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence`

after downgrade to gradio 4.21.0 the issue disappear.
so maybe should freeze gradio version

btw, it's better to upgrade bitsandbytes to the latest version to use official Windows build.

### CODE REVIEW

**Comment by Jarcis-cy** [comment]
Installing vqa using your branch will report an error: `UnicodeDecodeError: 'gbk' codec can't decode byte 0xa3 in position 24: illegal multibyte sequence`

I don't know if it's a problem with your branch or the code itself, because if I don't use your branch, my code doesn't run at all and reports the same error as you do

**Comment by ananosleep** [comment]
bitsandbytes=0.43.0 is not available in mirror.baidu.com.
maybe I should consider to switch to mirror from tsinghua

**Comment by Jarcis-cy** [comment]
> Installing vqa using your branch will report an error: `UnicodeDecodeError: 'gbk' codec can't decode byte 0xa3 in position 24: illegal multibyte sequence`
> 
> I don't know if it's a problem with your branch or the code itself, because if I don't use your branch, my code doesn't run at all and reports the same error as you do

This problem will also occur in the official code. . . I don’t know which dependency is causing it, so I can only try switching to linux.

**Comment by ananosleep** [comment]
trying to reproduce...
could you upload your error logs？

**Comment by ananosleep** [comment]
> > Installing vqa using your branch will report an error: `UnicodeDecodeError: 'gbk' codec can't decode byte 0xa3 in position 24: illegal multibyte sequence`
> > I don't know if it's a problem with your branch or the code itself, because if I don't use your branch, my code doesn't run at all and reports the same error as you do
> 
> This problem will also occur in the official code. . . I don’t know which dependency is causing it, so I can only try switching to linux.

trying to reproduce...
could you upload your error logs？

**Comment by Jarcis-cy** [comment]
image
```
Traceback (most recent call last):
  File "F:\AI\GPT4V-Image-Captioner\myenv\lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "F:\AI\GPT4V-Image-Captioner\myenv\lib\site-packages\gradio\route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\AI\GPT4V-Image-Captioner\myenv\lib\site-packages\gradio\blocks.py", line 1695, in process_api
    result = await self.call_function(
  File "F:\AI\GPT4V-Image-Captioner\myenv\lib\site-packages\gradio\blocks.py", line 1235, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\AI\GPT4V-Image-Captioner\myenv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "F:\AI\GPT4V-Image-Captioner\myenv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "F:\AI\GPT4V-Image-Captioner\myenv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "F:\AI\GPT4V-Image-Captioner\myenv\lib\site-packages\gradio\utils.py", line 692, in wrapper
    response = f(*args, **kwargs)
  File "F:\AI\GPT4V-Image-Captioner\lib\Api_Utils.py", line 253, in installer
    result_string = file.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa3 in position 24: illegal multibyte sequence
```
image

**Comment by Jarcis-cy** [comment]
I can't seem to get it to work on linux either....

Error installing dependencies manually
image

Downloading the model yourself on hf and clicking install doesn't work either
image

**Pull request closed without merging**
